{
 "title": "Microsoft SQL Server Dashboard Simplified",
 "description": "This is a comprehensive Microsoft SQL Server Dashboard designed to monitor key performance indicators. It provides real-time insights into your SQL Server environment.",
 "tags": [ "sqlserver" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "table",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "date" } },
     "targets": [
      {
       "dataset": "DemoDB",
       "rawSql": "SELECT sqlserver_start_time as 'SQL SERVER START TIME'\nFROM sys.dm_os_sys_info;\n"
      }
     ]
    },
    {
     "title": "Active User Sessions",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 16, "x": 8, "y": 1 },
     "targets": [
      {
       "dataset": "_DBA",
       "rawSql": "SELECT login_name AS LoginName,\n       COUNT(session_id) AS SessionCount\nFROM sys.dm_exec_sessions\nWHERE is_user_process = 1\nGROUP BY login_name\nORDER BY SessionCount DESC;\n"
      }
     ]
    },
    {
     "title": "Current Connections",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "DemoDB",
       "rawSql": "SELECT COUNT(session_id) AS Connections\nFROM sys.dm_exec_sessions\nWHERE is_user_process = 1;\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 Longest Running Queries",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "dataset": "DemoDB",
       "rawSql": "SELECT TOP 10\n    qs.total_elapsed_time / qs.execution_count / 1000.0 AS avg_duration_ms,\n    qs.execution_count,\n    SUBSTRING(qt.text, qs.statement_start_offset/2,\n              (CASE\n                  WHEN qs.statement_end_offset = -1 THEN LEN(CONVERT(NVARCHAR(MAX), qt.text)) * 2\n                  ELSE qs.statement_end_offset\n               END - qs.statement_start_offset)/2) AS query_text\nFROM sys.dm_exec_query_stats qs\nCROSS APPLY sys.dm_exec_sql_text(qs.sql_handle) qt\nORDER BY avg_duration_ms DESC;"
      }
     ]
    },
    {
     "title": "Execution Plans Performance",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "dataset": "_DBA",
       "rawSql": "SELECT TOP 10\n       st.text AS QueryText,\n       qs.total_worker_time AS CPUTime,\n       qs.total_elapsed_time AS TotalTime,\n       qs.total_logical_reads AS LogicalReads\nFROM sys.dm_exec_query_stats qs\nCROSS APPLY sys.dm_exec_sql_text(qs.sql_handle) st\nORDER BY qs.total_worker_time DESC;\n"
      }
     ]
    },
    {
     "title": "Query Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 21 },
     "targets": [
      {
       "dataset": "_DBA",
       "rawSql": "SELECT TOP 10\n       creation_time AS CreationTime,\n       total_logical_reads AS LogicalReads\nFROM sys.dm_exec_query_stats\nORDER BY total_elapsed_time DESC;\n"
      }
     ]
    },
    {
     "title": "Query Cache Hit Rate",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "DemoDB",
       "rawSql": "SELECT \n    (CAST(SUM(CASE WHEN usecounts > 0 THEN 1 ELSE 0 END) AS FLOAT) / COUNT(*)) * 100 AS Cache_Hit_Ratio\nFROM sys.dm_exec_cached_plans\nWHERE objtype = 'Adhoc'\n    OR objtype = 'Prepared';\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Server Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running Threads",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "DemoDB",
       "rawSql": "SELECT COUNT(*) AS Running_Threads\nFROM sys.dm_exec_requests\nWHERE status = 'running';\n"
      }
     ]
    },
    {
     "title": "Table Locks",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 18, "x": 6, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dataset": "DemoDB",
       "rawSql": "SELECT \n    request_session_id AS SessionID,\n    resource_database_id AS DatabaseID,\n    resource_associated_entity_id AS EntityID,\n    request_mode AS LockType,\n    request_status AS Status\nFROM sys.dm_tran_locks;\n"
      }
     ]
    },
    {
     "title": "Open Files Limit",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "DemoDB",
       "rawSql": "SELECT \n    COUNT(*) AS OpenFiles\nFROM sys.dm_io_pending_io_requests;\n"
      }
     ]
    },
    {
     "title": "Temp Tables Created On Disk",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "DemoDB",
       "rawSql": "SELECT \n    SUM(user_objects_alloc_page_count) AS 'User Object Pages',\n    SUM(internal_objects_alloc_page_count) AS 'Internal Object Pages'\nFROM sys.dm_db_session_space_usage;\n"
      }
     ]
    }
   ]
  },
  { "title": "Buffer and Index Management", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Buffer Pool Hit Rate",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "DemoDB",
     "rawSql": "SELECT \n    CAST(COUNT(*) * 8.0 / 1024 AS DECIMAL(10, 2)) AS 'Buffer Pool Used MB',\n    CAST(SUM(CASE WHEN is_modified = 1 THEN 1 ELSE 0 END) * 8.0 / 1024 AS DECIMAL(10, 2)) AS 'Dirty Buffer MB',\n    CAST(COUNT(*) * 8.0 / 1024 AS DECIMAL(10, 2)) AS 'Buffer Pool Total MB',\n    CAST(SUM(CASE WHEN is_modified = 1 THEN 1 ELSE 0 END) * 8.0 / 1024 AS DECIMAL(10, 2)) AS 'Dirty Buffer Used MB'\nFROM sys.dm_os_buffer_descriptors\nWHERE database_id > 4;\n"
    }
   ]
  },
  {
   "title": "Buffer Pool Usage",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "DemoDB",
     "rawSql": "SELECT \n    (total_physical_memory_kb / 1024) AS 'Total Physical Memory MB',\n    (available_physical_memory_kb / 1024) AS 'Available Physical Memory MB',\n    (total_page_file_kb / 1024) AS 'Total Page File MB',\n    (available_page_file_kb / 1024) AS 'Available Page File MB',\n    (system_memory_state_desc) AS 'System Memory State Description'\nFROM sys.dm_os_sys_memory;\n"
    }
   ]
  },
  {
   "title": "Page Life Expectancy",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 4 },
   "targets": [
    {
     "dataset": "_DBA",
     "rawSql": "SELECT [object_name], [counter_name], [cntr_value] AS PageLifeExpectancy\nFROM sys.dm_os_performance_counters\nWHERE [object_name] LIKE '%Buffer Manager%'\nAND [counter_name] = 'Page life expectancy';\n"
    }
   ]
  },
  {
   "title": "Index Usage",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "DemoDB",
     "rawSql": "SELECT \n    OBJECT_NAME(s.object_id) AS TableName,\n    i.name AS IndexName,\n    s.user_seeks,\n    s.user_scans,\n    s.user_lookups,\n    s.user_updates\nFROM sys.dm_db_index_usage_stats AS s\nINNER JOIN sys.indexes AS i ON i.object_id = s.object_id AND i.index_id = s.index_id\nWHERE s.database_id = DB_ID(DB_NAME())\nORDER BY s.user_seeks DESC;\n"
    }
   ]
  },
  { "title": "Database Space Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Total Space MB",
   "type": "bargauge",
   "description": "modify the max with the size of your disk associated with the database",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "DemoDB",
     "rawSql": "SELECT \n    ISNULL(t.NAME, 'Total') AS TableName,\n    ISNULL(s.NAME, '') AS SchemaName,\n    CAST(ROUND(((SUM(a.total_pages) * 8) / 1024.0), 2) AS DECIMAL(18, 2)) AS TotalSpaceMB\nFROM \n    sys.tables t\nINNER JOIN      \n    sys.indexes i ON t.OBJECT_ID = i.object_id\nINNER JOIN \n    sys.partitions p ON i.object_id = p.OBJECT_ID AND i.index_id = p.index_id\nINNER JOIN \n    sys.allocation_units a ON p.partition_id = a.container_id\nINNER JOIN \n    sys.schemas s ON t.schema_id = s.schema_id\nGROUP BY \n    ROLLUP(t.Name, s.Name)\nORDER BY \n    CASE WHEN t.Name IS NULL THEN 1 ELSE 0 END,\n    TotalSpaceMB DESC;\n"
    }
   ]
  },
  {
   "title": "Used Space MB",
   "type": "bargauge",
   "description": "modify the max with the size of your disk associated with the database",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "DemoDB",
     "rawSql": "SELECT \n    ISNULL(t.NAME, 'Total') AS TableName,\n    ISNULL(s.NAME, '') AS SchemaName,\n    CAST(ROUND(((SUM(a.used_pages) * 8) / 1024.0), 2) AS DECIMAL(18, 2)) AS UsedSpaceMB\nFROM \n    sys.tables t\nINNER JOIN      \n    sys.indexes i ON t.OBJECT_ID = i.object_id\nINNER JOIN \n    sys.partitions p ON i.object_id = p.OBJECT_ID AND i.index_id = p.index_id\nINNER JOIN \n    sys.allocation_units a ON p.partition_id = a.container_id\nINNER JOIN \n    sys.schemas s ON t.schema_id = s.schema_id\nGROUP BY \n    ROLLUP(t.Name, s.Name)\nORDER BY \n    CASE WHEN t.Name IS NULL THEN 1 ELSE 0 END,\n    UsedSpaceMB DESC;\n"
    }
   ]
  },
  {
   "title": "Unused Space MB",
   "type": "bargauge",
   "description": "modify the max with the size of your disk associated with the database",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "DemoDB",
     "rawSql": "SELECT \n    ISNULL(t.NAME, 'Total') AS TableName,\n    ISNULL(s.NAME, '') AS SchemaName,\n    CAST(ROUND(((SUM(a.total_pages - a.used_pages) * 8) / 1024.0  * 100), 2) AS DECIMAL(18, 2)) AS UnusedSpaceMB\nFROM \n    sys.tables t\nINNER JOIN      \n    sys.indexes i ON t.OBJECT_ID = i.object_id\nINNER JOIN \n    sys.partitions p ON i.object_id = p.OBJECT_ID AND i.index_id = p.index_id\nINNER JOIN \n    sys.allocation_units a ON p.partition_id = a.container_id\nINNER JOIN \n    sys.schemas s ON t.schema_id = s.schema_id\nGROUP BY \n    ROLLUP(t.Name, s.Name)\nORDER BY \n    CASE WHEN t.Name IS NULL THEN 1 ELSE 0 END,\n    UnusedSpaceMB DESC;\n"
    }
   ]
  },
  {
   "title": "Row Count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "DemoDB",
     "rawSql": "SELECT \n    ISNULL(t.NAME, 'Total') AS TableName,\n    ISNULL(s.NAME, '') AS SchemaName,\n    SUM(p.rows) AS RowCounts\nFROM \n    sys.tables t\nINNER JOIN      \n    sys.indexes i ON t.OBJECT_ID = i.object_id\nINNER JOIN \n    sys.partitions p ON i.object_id = p.OBJECT_ID AND i.index_id = p.index_id\nINNER JOIN \n    sys.schemas s ON t.schema_id = s.schema_id\nGROUP BY \n    ROLLUP(t.Name, s.Name)\nORDER BY \n    CASE WHEN t.Name IS NULL THEN 1 ELSE 0 END,\n    RowCounts DESC;\n"
    }
   ]
  },
  {
   "title": "Transaction Log Space Usage",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "rawSql": "dbcc sqlperf (logspace)" }
   ]
  },
  {
   "title": "Database File Usage",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "_DBA",
     "rawSql": "SELECT name AS FileName,\n       size/128 AS FileSizeMB,\n       physical_name AS PhysicalName\nFROM sys.master_files;\n"
    }
   ]
  },
  {
   "title": "Backup Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "dataset": "_DBA",
     "rawSql": "SELECT database_name, \n       backup_start_date, \n       backup_finish_date, \n       backup_size / 1024 / 1024 AS BackupSizeMB\nFROM msdb.dbo.backupset\nORDER BY backup_start_date DESC;\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "_DBA",
     "rawSql": "SELECT \n    CAST(total_physical_memory_kb / 1024.0 / 1024.0 AS DECIMAL(10,2)) AS Total_Physical_Memory_GB,\n    CAST(available_physical_memory_kb / 1024.0 / 1024.0 AS DECIMAL(10,2)) AS Available_Physical_Memory_GB,\n    CAST(total_page_file_kb / 1024.0 / 1024.0 AS DECIMAL(10,2)) AS Total_Page_File_GB,\n    CAST(available_page_file_kb / 1024.0 / 1024.0 AS DECIMAL(10,2)) AS Available_Page_File_GB\nFROM sys.dm_os_sys_memory;"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "_DBA",
     "rawSql": "SELECT \n    SUM(CAST(mf.size * 8.0 / 1024 / 1024 AS DECIMAL(10,2))) AS FileSize_GB,\n    SUM(CAST((mf.size - FILEPROPERTY(mf.name, 'SpaceUsed')) * 8.0 / 1024 / 1024 AS DECIMAL(10,2))) AS FreeSpace_GB,\n    vs.total_bytes / 1024.0 / 1024 / 1024 AS DriveSize_GB,\n    vs.available_bytes / 1024.0 / 1024 / 1024 AS DriveFreeSpace_GB\nFROM sys.master_files mf\nINNER JOIN sys.databases db ON db.database_id = mf.database_id\nCROSS APPLY sys.dm_os_volume_stats(mf.database_id, mf.file_id) vs\nGROUP BY vs.total_bytes, vs.available_bytes"
    }
   ]
  },
  { "title": "Jobs Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Job Execution Frequency",
   "type": "bargauge",
   "description": "Last 7 days",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 61 },
   "targets": [
    {
     "dataset": "_DBA",
     "rawSql": "SELECT job.name AS JobName,\n       COUNT(run.run_date) AS ExecutionCount\nFROM msdb.dbo.sysjobs AS job\nINNER JOIN msdb.dbo.sysjobhistory AS run\nON job.job_id = run.job_id\nWHERE run.run_date >= CONVERT(VARCHAR, GETDATE() - 7, 112)  -- Last 7 days\nGROUP BY job.name\nORDER BY ExecutionCount DESC\n"
    }
   ]
  },
  {
   "title": "Scheduled and Running Jobs",
   "type": "table",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 61 },
   "targets": [
    {
     "dataset": "_DBA",
     "rawSql": "SELECT\n       job.name AS JobName,\n       CASE\n           WHEN activity.run_requested_date IS NULL THEN 'Scheduled'\n           ELSE 'Running'\n       END AS JobStatus,\n       schedule.next_run_date AS NextRunDate,\n       schedule.next_run_time AS NextRunTime\nFROM msdb.dbo.sysjobs AS job\nLEFT JOIN msdb.dbo.sysjobactivity AS activity ON job.job_id = activity.job_id\nLEFT JOIN msdb.dbo.sysjobschedules AS schedule ON job.job_id = schedule.job_id\nWHERE  schedule.next_run_date IS NOT NULL       -- Scheduled jobs\nORDER BY schedule.next_run_date, schedule.next_run_time"
    }
   ]
  },
  {
   "title": "Failed Jobs Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 67 },
   "targets": [
    {
     "dataset": "_DBA",
     "rawSql": "SELECT job.name AS JobName,\n       run.run_date AS RunDate,\n       run.run_time AS RunTime,\n       run.run_duration AS RunDuration,\n       run.message AS ErrorMessage\nFROM msdb.dbo.sysjobs AS job\nINNER JOIN msdb.dbo.sysjobhistory AS run\nON job.job_id = run.job_id\nWHERE run.run_status = 0  -- 0 indicates failure\nORDER BY run.run_date DESC\n"
    }
   ]
  },
  {
   "title": "Jobs in progress",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 73 },
   "targets": [
    {
     "dataset": "_DBA",
     "rawSql": "SELECT DISTINCT \n       job.name AS JobName,\n       activity.run_requested_date AS StartTime,\n       DATEDIFF(SECOND, activity.run_requested_date, GETDATE()) AS RunDurationSeconds\nFROM msdb.dbo.sysjobs AS job\nINNER JOIN msdb.dbo.sysjobactivity AS activity\n    ON job.job_id = activity.job_id\nWHERE activity.run_requested_date IS NOT NULL\n  AND activity.stop_execution_date IS NULL\nORDER BY activity.run_requested_date DESC;\n"
    }
   ]
  },
  {
   "title": "Job Execution History Duration",
   "type": "table",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 73 },
   "targets": [
    {
     "dataset": "_DBA",
     "rawSql": "SELECT job.name AS JobName,\n       run.run_date AS RunDate,\n       run.run_duration AS RunDuration\nFROM msdb.dbo.sysjobs AS job\nINNER JOIN msdb.dbo.sysjobhistory AS run\nON job.job_id = run.job_id\nWHERE run.step_id = 0  -- 0 indicates job level information\nORDER BY run.run_date DESC\n"
    }
   ]
  }
 ]
}